@startuml

hide empty methods

class Usager #LightPink

class Statut #LightYellow 

class PeriodeScolaire #PeachPuff {
    idPeriodeScolaire : Identifiant [1..1]
    dateDebutPeriodeScolaire : Date [0..1]
    dateFinPeriodeScolaire : Date [0..1]
    niveauScolaireReel : ConceptCode [0..1]
    niveauScolaireSuivi : ConceptCode [0..1]
    typeEnseignementSpecialise : ConceptCode [0..*]
    referentScolaire : PersonnePhysique [0..1]
    contactReferentScolaire  : Telecommunication [0..*]
    ecole : EntiteGeographique [0..1]
    diplome : ConceptCode [0..*]
    volumeScolarisation : Numerique [0..1]
    commentaireAnneeScolaire : Texte [0..1]
}

class ProjetVie #PeachPuff {
    idProjetVie : Identifiant [1..1]
    titreProjetVie : Texte [1..1]
    dateDebutProjetVie : Date [0..1]
    dateFinProjetVie : Date [0..1]
    aspirationSouhait : Texte [0..*]
    }

Usager "1" -- "*" PeriodeScolaire
Usager "1" - "*" ProjetVie

ProjetVie "1" - "1" Statut

@enduml