@startuml

hide empty methods

class Usager #LightPink

class PersonnePhysique #LightYellow

class PeriodeScolaire #PeachPuff {
    idPeriodeScolaire : Identifiant [1..1]
    dateDebutPeriodeScolaire : Date [0..1]
    dateFinPeriodeScolaire : Date [0..1]
    niveauScolaireReel : ConceptCode [0..1]
    niveauScolaireSuivi : ConceptCode [0..1]
    typeEnseignementSpecialise : ConceptCode [0..*]
    ecole : EntiteGeographique [0..1]
    diplome : ConceptCode [0..*]
    volumeScolarisation : Numerique [0..1]
    commentaireAnneeScolaire : Texte [0..1]
}

class ReferentScolaire #PeachPuff {
    contactReferentScolaire  : Telecommunication [0..*]
}

Usager "1" - "*" PeriodeScolaire
PersonnePhysique <|-- ReferentScolaire
PeriodeScolaire "1" - "1" ReferentScolaire

@enduml