@startuml

"Producteur : Logiciel DUI" -> "Consommateur : SI Tiers" : Flux 1.1 **Transmission données DUI**
"Producteur : Logiciel DUI" <-- "Consommateur : SI Tiers" : Flux 1.2 **Resultat transmission données DUI**
@enduml
