@startuml

map "item" as item #DarkGray {
    commentaire => text
    resultatEvaluation => answer.valueCoding
    premier_niveau_DetailEvaluation => item.item
    resultatChampsEvalue_niveau1 => item.item.answer
    commentaireEvaluation_niveau1 => item.item.text
    deuxieme_niveau_DetailEvaluation => item.item.item
    resultatChampsEvalue_niveau2 => item.item.item.answer
    commentaireEvaluation_niveau2 => item.item.item.text
}

map "meta" as meta #DarkGray {
    Statut.dateStatut => lastUpdated
}

map "status" as status #DarkGray {
    Statut.motifNonRealisation => <&plus> TDDUICancelReason
}

object "**TDDUIPatient**" as TDDUIPatient_subject #80b1d3 {
    Usager
}

object "**TDDUIPractitioner**" as TDDUIPractitioner_author #fccde5 {
    Auteur
}

object "**TDDUIPractitioner**" as TDDUIPractitioner_source #fccde5 {
    Evaluateur
}

map "**Evaluation : TDDUIQuestionnaireResponse**" as Evaluation #d9d9d9 {
    Responsable => <&plus> TDDUIResponsible
    pieceJointeEvaluation => <&plus> TDDUIAttachment
    idEvaluation => identifier
    dateEvaluation => authored
}

Evaluation -u-> meta
Evaluation -> status
Evaluation -l-> item

Evaluation --> TDDUIPatient_subject : subject
Evaluation --> TDDUIPractitioner_author : author
Evaluation --> TDDUIPractitioner_source : source

@enduml