@startuml

'Declaration des éléments
rectangle "Vue fonctionnelle DUI" {

    rectangle "Sejour \n [[StructureDefinition-tddui-encounter-sejour.html TDDUI Encounter Sejour]] " as Sejour #LightSkyBlue;line:Black;text:Black

    rectangle "Entité juridique \n [[StructureDefinition-tddui-organization.html TDDUI Organization]]" as EJ #Gold;line:Black;text:Black

    rectangle "Usager \n [[StructureDefinition-tddui-patient.html TDDUI Patient]] \n [[StructureDefinition-tddui-patient-ins.html TDDUI Patient INS]]" as Usager #LimeGreen;line:Black;text:Black
}

'Liens entre éléments
Usager "1"--"*" Sejour
Sejour "1..*"--"1" EJ

@enduml
