@startuml

map "component" as component #DarkGray {
    observationAmenagement => value[x]
}

map "**MobiliteUsager : TDDUIObservationMobiliteUsager**" as MobiliteUsager #fb8072 {
    type => value[x]
    component *-> component
}


@enduml