@startuml

object "**TDDUIPractitioner**" as TDDUIPractitioner #b3de69 {
    Auteur
}

object "**TDDUIPatient**" as TDDUIPatient_subject #fdb462 {
    Usager
}

map "**Accord : TDDUIConsentAccord**" as Accord #8dd3c7 {
    dureeValidite => <&plus> TDDUI-consentPeriod-r5
    dateSignature => dateTime
}

Accord -u-> TDDUIPractitioner : performer
Accord -u-> TDDUIPatient_subject : performer

@enduml