@startuml

map "<&layers> name:usualName" as nameusualName #back:WhiteSmoke;header:LightGray {
    nomUsage => family
    prenomUtilise => given
}

map "<&layers> name:officialName" as nameofficialName #back:WhiteSmoke;header:LightGray {
    prenom => <&plus> birth-list-given-name
    nomNaissance => family
    premierPrenomActeNaissance => given
    civilite => prefix
}

map "**Usager : TDDUIPatient**" as Usager #back:TECHNOLOGY;header:LimeGreen {
    paysNaissance => <&plus> birthPlace.value[x].country
    communeNaissance => <&plus> birthPlace.value[x].extension:inseeCode
    numSecuriteSociale => <&layers> identifier:NSS
    identifiantLocalUsagerESSMS => <&layers> identifier:PI
    numeroIndividuInitial => <&layers> identifier:InitialNumberMDPH
    sexe => gender
    dateNaissance => birthDate
    <&layers> name:usualName *--> nameusualName
    <&layers> name:officialName *-> nameofficialName
}

map "component" as component #DarkGray {
    causeMortalite => <&layers> value[x]:valueCodeableConcept
}

map "**CauseMortalite : TDDUIObservationCauseMortalite**" as CauseMortalite #fb8072 {
    component *-> component
}

map "component" as componentMobilite #DarkGray {
    observationAmenagement => value[x]
}

map "**MobiliteUsager : TDDUIObservationMobiliteUsager**" as MobiliteUsager #fb8072 {
    type => value[x]
    component *-> componentMobilite
}

Usager -u-> CauseMortalite
Usager --> MobiliteUsager


@enduml