@startuml

hide empty methods

class TDDUIPatient_et_INS #LightPink
class TDDUIGoalAttente #LightGray
class TDDUIServiceRequestBesoin #LightGray
class TDDUIGoalObjectif #LightGray
class TDDUITaskAction #LightGray
class TDDUITaskMoyenRessource #LightGray
class TDDUITaskPrestation #LightGray
class TDDUITaskBilan #LightGray
class TDDUICarePlanProjetPerso #LightGray

TDDUIPatient_et_INS <-- TDDUICarePlanProjetPerso : CarePlan.subject (1..1)

TDDUICarePlanProjetPerso <-- TDDUIServiceRequestBesoin : ServiceRequest.basedOn (1..1)
TDDUICarePlanProjetPerso <-- TDDUIGoalObjectif : Goal.extension[TDDUICarePlanProjetPerso] (1..1)
TDDUICarePlanProjetPerso <-- TDDUITaskAction : task.basedOn (1..1)
TDDUICarePlanProjetPerso <-- TDDUITaskMoyenRessource : task.basedOn (1..1)

TDDUIServiceRequestBesoin <- TDDUIGoalObjectif : TDDUIServiceRequestBesoin.addresses (0..*)
TDDUIGoalObjectif <- TDDUITaskAction : TDDUITaskAction.input (0..*)
TDDUITaskAction <- TDDUITaskMoyenRessource : TDDUITaskMoyenRessource.partOf (0..1)

TDDUITaskAction <-- TDDUITaskPrestation : TDDUITaskPrestationProjetPerso.partOf (0..1)
TDDUICarePlanProjetPerso <- TDDUITaskPrestation : task.basedOn (1..1)

TDDUICarePlanProjetPerso <- TDDUITaskBilan : task.basedOn (1..1)
TDDUIGoalAttente -> TDDUICarePlanProjetPerso : Goal.extension[TDDUICarePlanProjetPerso] (1..1)

@enduml