@startuml

map "**MobiliteUsager : TDDUIObservationMobiliteUsager**" as MobiliteUsager #fb8072 {
    type => value[x]
    observationAmenagement => component.value[x]
}

object "**TDDUIPatient/TDDUIPatientINS**" as TDDUIPatient #fdb462 {
    Usager
}

MobiliteUsager --> TDDUIPatient : subject
@enduml