@startuml

map "meta" as meta #DarkGray {
    dateModificationEvenement => lastUpdated
}

map "Statut.statut : status" as Statutstatut #DarkGray {
    statut.motifNonRealisation => <&plus> tddui-cancel-reason
}

map "participant" as participant #DarkGray {
    statut.auteur => type
}

map "period" as period #DarkGray {
    dateDebutEvenement => start
    dateFinEvenement => end
}

object "**TDDUIPatient**" as TDDUIPatient #fdb462 {
    Usager
}

object "**TDDUIPractitioner**" as TDDUIPractitioner #d9d9d9 {
    Professionnel
}

object "**TDDUIOrganization**" as TDDUIOrganization #bebada {
    structureEnCharge
}

object "**TDDUIEncounterSejour**" as TDDUIEncounterSejour #ffffb3 {
    sejour
}

map "**Événement : TDDUIEncounterEvenement**" as Événement #8dd3c7 {
    RessourceUtilisee => <&plus> TDDUIRessourcesUsed
    typeRessourceUtilisee => <&plus> TDDUIRessourcesUsed.extension:TDDUIRessourceType
    detailTypeRessourceUtilisee => <&plus> TDDUIRessourcesUsed.extension:TDDUIMaterialDetail
    detailTypeRessourceUtilisee => <&plus> TDDUIRessourcesUsed.extension:TDDUIFacilityResource
    libelleEvenement => <&plus> TDDUIEventLabel
    commentaireEvenement => <&plus> TDDUIComment
    compteRenduEvenement => <&plus> TDDUIEventReport
    pieceJointeEvenement => <&plus> TDDUIAttachment
    evenementHorsPrestation => <&plus> TDDUIEventOutsideService
    motifEvenement => <&plus> TDDUIEventReason
    usagerPresent => <&plus> TDDUIPatientPresent
    repas => <&plus> TDDUIMeal
    idEvenement => identifier
    typeEvenement => type
    lieuEvenement => location
    meta *-> meta
    Statut.statut => status
    participant *-> participant
    period *-> period
}

Événement::Statut.statut -u-> Statutstatut
Événement -d-> TDDUIPatient : subject
Événement -l-> TDDUIPractitioner : participant.individual
Événement -r-> TDDUIOrganization : serviceProvider
Événement -u-> TDDUIEncounterSejour : partOf

@enduml