@startuml

rectangle "UsagerINS \n [[StructureDefinition-tddui-patient-ins.html TDDUIPatientINS]]" as UsagerINS #80b1d3 
rectangle "Usager \n [[StructureDefinition-tddui-patient.html TDDUIPatient]]" as Usager #fdb462 
rectangle "Professionnel \n [[StructureDefinition-tddui-practitioner.html TDDUIPractitioner]]" as Practitioner #d9d9d9 
rectangle "ProfessionnelRole \n [[StructureDefinition-tddui-practitioner-role.html TDDUIPractitionerRole]]" as PractitionerRole #b3de69 
rectangle "EntiteJuridique \n [[StructureDefinition-tddui-organization.html TDDUIOrganization]]" as EntiteJuridique #bebada 

rectangle "Séjour \n [[StructureDefinition-tddui-encounter-sejour.html TDDUIEncounterSejour]]" as Sejour #ffffb3 
rectangle "Événement \n [[StructureDefinition-tddui-encounter-evenement.html TDDUIEncounterEvenement]]" as Evenement #8dd3c7 

rectangle "Transport \n [[StructureDefinition-tddui-task-transport.html TDDUITaskTransport]]" as Transport #ffed6f 
rectangle "TransportUsager \n [[StructureDefinition-tddui-task-transport-usager.html TDDUITaskTransportUsager]]" as TransportUsager #ccebc5 
rectangle "TransportProfessionnel \n [[StructureDefinition-tddui-task-transport-professionnel.html TDDUITaskTransportProfessionnel]]" as TransportProfessionnel #bc80bd 

Evenement -- "1..1" Usager
Evenement -- "1..1" UsagerINS
Evenement -- "0..1" PractitionerRole
Evenement -- "0..1" EntiteJuridique
Evenement -- "0..1" Sejour

Sejour -- "1..1" Usager
Sejour -- "1..1" UsagerINS
Sejour -- "1..1" EntiteJuridique

PractitionerRole -- "0..1" EntiteJuridique
PractitionerRole -- "1..1" Practitioner

Transport -- "1..1" Evenement
Transport -- "0..1" EntiteJuridique

TransportUsager -- "1..1" Evenement
TransportUsager -- "0..1" EntiteJuridique

TransportProfessionnel -- "1..1" Evenement
TransportProfessionnel -- "0..1" EntiteJuridique
TransportProfessionnel -- "1..1" PractitionerRole

@enduml