name: Workflow Sushi Tests gitHubpages
on:
  workflow_call:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run-sushi-tests_gitHubPages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:      
          path: igSource

      - name: Copy CDA folder
        run: |
              mkdir to_publish/ig
              path_spec="./igSource/input/cda"
              cp -r ./igSource/input/cda  ../to_publish/ig/cda

      - uses: ansforge/IG-workflows@v0.3.0
        with:      
          repo_ig: "./igSource"   
          github_page: "true"
          github_page_token: ${{ secrets.GITHUB_TOKEN }}
          bake: "false"
          validator_cli: "false"
          generate_testscript: "false"
          generate_plantuml : "true"


